export const movieMock = JSON.stringify({
    title: 'Аватар.Путь.воды.2022.TS.[1080p].NNMClub.mkv',
    magnet: '111F457342C2A841857E95A67F052F2C21B77219',
    fileName: 'Аватар. Путь воды (2022) HDTSRip 1080p.mkv',
    soutceUrl: 'soutceUrl',
    plot: 'plot',
    year: 'year',
    director: 'director',
    actors: [''],
    poster: '',
    trailer: '',
    boxOffice: '',
    released: '',
    writer: '',
    runtime: '',
    ratingImdb: '',
    imdbId: '',
    rated: '',
    genres: [''],
});
